---
- name: add repository
  get_url:
    url: "https://packagecloud.io/install/repositories/grafana/stable/config_file.repo?os=CentOS&dist={{ ansible_distribution_major_version }}&source=script"
    dest: /etc/yum.repos.d/grafana.repo
  tags:
    - grafana

- name: add rpm key
  rpm_key: state=present key=https://packagecloud.io/gpg.key
  tags:
    - grafana

- name: install package
  yum: name=grafana state=present
  tags:
    - grafana

- name: write configuration
  template: src=grafana.ini.j2 dest=/etc/grafana/grafana.ini
  notify:
    - restart grafana
  tags:
    - grafana

- name: setup as startup service
  service: name=grafana-server state=started enabled=yes
  tags:
    - grafana

