---
- name: add repository
  get_url:
    url: "https://packagecloud.io/install/repositories/grafana/stable/config_file.repo?os=CentOS&dist=6&source=script"
    dest: /etc/yum.repos.d/grafana.repo
  tags:
    - grafana

- name: install package
  yum: name=grafana state=present
  tags:
    - grafana

